const map = {addpersonbutton: "#differentApp > div > div.row.bordered-header > div.icon-bar.col-xs-3.row.end-xs > a:nth-child(3) > div",
suppliername: "#differentApp > div > div.content-dock > div > div > form > div.inner-form > div:nth-child(1) > div:nth-child(1) > input",
name: "#differentApp > div > div.content-dock > div > div > form > div.inner-form > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div > input",
email: "#differentApp > div > div.content-dock > div > div > form > div.inner-form > div:nth-child(1) > div:nth-child(3) > div:nth-child(2) > div > input",
address: "#differentApp > div > div.content-dock > div > div > form > div.inner-form > div:nth-child(1) > div:nth-child(3) > div:nth-child(3) > div > input",
phone: "#differentApp > div > div.content-dock > div > div > form > div.inner-form > div:nth-child(1) > div:nth-child(3) > div:nth-child(4) > div > div > div > div:nth-child(2) > ul > li:nth-child(2) > input",
sameasbillingcontactracticbox:"#differentApp > div > div.content-dock > div > div > form > div.inner-form > div:nth-child(1) > div:nth-child(4) > div > p > input[type=checkbox]",
name2: "#differentApp > div > div.content-dock > div > div > form > div.inner-form > div:nth-child(1) > div:nth-child(5) > div:nth-child(1) > div > input",
email2: "#differentApp > div > div.content-dock > div > div > form > div.inner-form > div:nth-child(1) > div:nth-child(5) > div:nth-child(2) > div > input",
address2:  "#differentApp > div > div.content-dock > div > div > form > div.inner-form > div:nth-child(1) > div:nth-child(5) > div:nth-child(3) > div > input",
phone2: "#differentApp > div > div.content-dock > div > div > form > div.inner-form > div:nth-child(1) > div:nth-child(5) > div:nth-child(4) > div > div > div > div:nth-child(2) > ul > li:nth-child(2) > input",
website:  "#differentApp > div > div.content-dock > div > div > form > div.inner-form > div:nth-child(1) > div:nth-child(7) > input",
advisory:"input[name = Advisory]",
buildingmanager: "input[name = 'Building Manager']",
council: "input[name = Council]",
insurance: "input[name = Insurance]",
ac:"input[name = AC]",
applianceinstalls: "input[name = 'Appliance Installs']",
appliancerepairs:"input[name = 'Appliance Repairs']",
blinds: "input[name = Blinds]",
builder: "input[name = Builder]",
cleaners:  "input[name = Cleaners]",
electrical:"input[name = Electrical]",
fence: "input[name = Fence]",
flooring:"input[name = Flooring]",
garagedoor:"input[name = 'Garage Door']", 
glazier:  "input[name = Glazier]",
handyman: "input[name = Handyman]",
heating: "input[name = Heating]",
hotWater: "input[name = 'Hot Water']",
  "lawn/gardening": {
    "selector": "input[name = 'Lawn/Gardening']"
  },
locksmith: "input[name = Locksmith]",
mould:"input[name = Mould]",
painting:"input[name = Painting]",
pestcontrol:"input[name = 'Pest Control']",
plumbing: "input[name = Plumbing]",
pool: "input[name = Pool]",
removalist:"input[name = Removalist]",
security: "input[name = Security]",
smokealarms:"input[name = 'Smoke Alarms']",
solarpanels: "input[name = 'Solar Panels']",
marketing: "input[name = Marketing]",
strata:"input[name = Strata]",
tribunal: "input[name = Tribunal]",
water: "#differentApp > div > div.content-dock > div > div > form > div.inner-form > div:nth-child(1) > div.business-category-multi-select > div:nth-child(2) > div > div:nth-child(9) > div.level-1-categories > input[type=checkbox]",
nsw: "#differentApp > div > div.content-dock > div > div > form > div.inner-form > div:nth-child(1) > div.service-zone-multi-select > div > div > div > div:nth-child(1) > div:nth-child(1) > input[type=checkbox]",
vic: "#differentApp > div > div.content-dock > div > div > form > div.inner-form > div:nth-child(1) > div.service-zone-multi-select > div > div > div > div:nth-child(2) > div:nth-child(1) > input[type=checkbox]",
qld: "#differentApp > div > div.content-dock > div > div > form > div.inner-form > div:nth-child(1) > div.service-zone-multi-select > div > div > div > div:nth-child(3) > div:nth-child(1) > input[type=checkbox]",
isgoodforurgentrequests: "input[name = isGoodForUrgentRequests]",
isavailableonweekends: "input[name = isAvailableOnWeekends]",
isavailableoutsidenormalhours: "input[name = isAvailableOutsideNormalHours]",
calloutfee: ".contact-sub-form input[name='callOutfee']",
emergehcycallfee: ".contact-sub-form input[name='emergencyCallOutfee']",
notes: "#differentApp > div > div.content-dock > div > div > form > div.inner-form > div:nth-child(1) > div:nth-child(14) > div:nth-child(4) > div > textarea",
abn: "#differentApp > div > div.content-dock > div > div > form > div.inner-form > div:nth-child(1) > div:nth-child(16) > input",
bsb: "#bsb",
accountno: "#accountNumber",
accountholder: "#accountHolderName",
upload: "#differentApp > div > div.content-dock > div > div > form > div.inner-form > div:nth-child(1) > div:nth-child(22) > div > div > div > div",
savebutton:"#differentApp > div > div.content-dock > div > div > form > div.inner-form > div.person-role-form > div > button.button.button_main"
  };